name: Build

on:
  workflow_dispatch:
    inputs:
      java:
        description: "The java version to run the test on"
        type: choice
        options:
          - "8"
      os:
        description: "The operating system to run the test on"
        type: choice
        options:
          - ubuntu-latest
          - macos-latest
          - windows-latest
  workflow_call:
    inputs:
      java:
        type: number
      os:
        type: string

jobs:
  compile:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java }}
          distribution: "temurin"
          cache: "maven"
      - name: build IGinX
        run: |
          mvn clean compile --batch-mode -DskipTests -P-format
      - name: upload compiled files
        uses: actions/upload-artifact@v4
        with:
          name: compiled-iginx
          if-no-files-found: error
          path: |
            "*"
            !".github/**"
            !".git/**"

  test:
    needs: compile
    runs-on: ${{ inputs.os }}
    steps:
      - uses: ./.github/actions/build
        with:
          os: ${{ inputs.os }}
          java: ${{ inputs.java }}
      - run: |
          mvn test --batch-mode -P-format -P-thrift-generation

  package:
    needs: compile
    runs-on: ${{ inputs.os }}
    steps:
      - uses: ./.github/actions/build
        with:
          os: ${{ inputs.os }}
          java: ${{ inputs.java }}
      - shell: bash
        run: |
          mvn package --batch-mode -DskipTests -P-format -P release -P-thrift-generation
      - uses: actions/upload-artifact@v4
        with:
          name: packaged-iginx-${{ inputs.os }}-${{ inputs.java }}
          if-no-files-found: error
          path: "assembly/target/iginx-assembly-*-server/*"